# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: collect-clinical-trials

on:
#   schedule:
#   # Run at 0 minute past every 12th hour
#     - cron:  '0 */12 * * *'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  collect-clinical-trials:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
    - name: Collect Clinical Trials Summary
      run: |
        python scripts/clinical-trials-extractor.py
        
    - name: Collect Clinical Trials Full
      run: |
        python scripts/clinical-trials-extractor-full.py

    - uses: stefanzweifel/git-auto-commit-action@v4.1.6
      with:
        commit_message: Commit new datasets
        branch: ${{ github.head_ref }}
        commit_user_name: Jake Barrett
        commit_user_email: jake.barrett@hdruk.ac.uk
        commit_author: Jake Barrett <jake.barrett@hdruk.ac.uk>
